//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anuncio", Namespace="http://schemas.datacontract.org/2004/07/BienvenidosUyBLL.EntidadesNegocio")]
    [System.SerializableAttribute()]
    public partial class Anuncio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionAnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWCF.ServiceReference1.Temporada[] FeriadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteWCF.ServiceReference1.Foto[] FotosAnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlojamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioBaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionAnuncio {
            get {
                return this.DescripcionAnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionAnuncioField, value) != true)) {
                    this.DescripcionAnuncioField = value;
                    this.RaisePropertyChanged("DescripcionAnuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWCF.ServiceReference1.Temporada[] Feriados {
            get {
                return this.FeriadosField;
            }
            set {
                if ((object.ReferenceEquals(this.FeriadosField, value) != true)) {
                    this.FeriadosField = value;
                    this.RaisePropertyChanged("Feriados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteWCF.ServiceReference1.Foto[] FotosAnuncio {
            get {
                return this.FotosAnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.FotosAnuncioField, value) != true)) {
                    this.FotosAnuncioField = value;
                    this.RaisePropertyChanged("FotosAnuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlojamiento {
            get {
                return this.IdAlojamientoField;
            }
            set {
                if ((this.IdAlojamientoField.Equals(value) != true)) {
                    this.IdAlojamientoField = value;
                    this.RaisePropertyChanged("IdAlojamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAnuncio {
            get {
                return this.NombreAnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAnuncioField, value) != true)) {
                    this.NombreAnuncioField = value;
                    this.RaisePropertyChanged("NombreAnuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrecioBase {
            get {
                return this.PrecioBaseField;
            }
            set {
                if ((this.PrecioBaseField.Equals(value) != true)) {
                    this.PrecioBaseField = value;
                    this.RaisePropertyChanged("PrecioBase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Temporada", Namespace="http://schemas.datacontract.org/2004/07/BienvenidosUyBLL.EntidadesNegocio")]
    [System.SerializableAttribute()]
    public partial class Temporada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_anuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_anuncio {
            get {
                return this.Id_anuncioField;
            }
            set {
                if ((this.Id_anuncioField.Equals(value) != true)) {
                    this.Id_anuncioField = value;
                    this.RaisePropertyChanged("Id_anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Foto", Namespace="http://schemas.datacontract.org/2004/07/BienvenidosUyBLL.EntidadesNegocio")]
    [System.SerializableAttribute()]
    public partial class Foto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anuncio {
            get {
                return this.AnuncioField;
            }
            set {
                if ((this.AnuncioField.Equals(value) != true)) {
                    this.AnuncioField = value;
                    this.RaisePropertyChanged("Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ListarAnuncios")]
    public interface ListarAnuncios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAnuncios/GetAll", ReplyAction="http://tempuri.org/ListarAnuncios/GetAllResponse")]
        ClienteWCF.ServiceReference1.Anuncio[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAnuncios/GetAll", ReplyAction="http://tempuri.org/ListarAnuncios/GetAllResponse")]
        System.Threading.Tasks.Task<ClienteWCF.ServiceReference1.Anuncio[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListarAnunciosChannel : ClienteWCF.ServiceReference1.ListarAnuncios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarAnunciosClient : System.ServiceModel.ClientBase<ClienteWCF.ServiceReference1.ListarAnuncios>, ClienteWCF.ServiceReference1.ListarAnuncios {
        
        public ListarAnunciosClient() {
        }
        
        public ListarAnunciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListarAnunciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarAnunciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarAnunciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWCF.ServiceReference1.Anuncio[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ClienteWCF.ServiceReference1.Anuncio[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
